### ISSUE TITLE
matchFlags should be used

### ISSUE THREAD

**Issue by way2muchnoise** [CyclopsMC/CommonCapabilitiesAPI#2]
Cause now it doesn't even matter what I pass :p

```
@Override
public ItemStack extractItem(@Nonnull ItemStack matchStack, int matchFlags, boolean simulate) {
    int slot = getNonEmptySlotWithItemStack(matchStack, ItemMatch.DAMAGE | ItemMatch.NBT);
    if (slot < 0) return null;
    return itemHandler.extractItem(slot, matchStack.stackSize, simulate);
}
```

https://github.com/CyclopsMC/CommonCapabilitiesAPI/blob/master-1.9/capability/itemhandler/SlotlessItemHandlerWrapper.java#L68

**Comment by rubensworks** [comment]
Oops, a bit too much copy-pasting here... Will fix tomorrow.

**Comment by way2muchnoise** [comment]
![](http://s2.quickmeme.com/img/03/03c56e3bccb5b06ecd2ab43cf193127d03053d3a7863e777cad55530af22a6e1.jpg)

#sorryNotSorry

**Comment by rubensworks** [comment]
@way2muchnoise You should now be able to use build 1.10.2-1.3.0-88 containing this fix.
