### ISSUE TITLE
Null pointer exception in ItemMatch.java

### ISSUE THREAD

**Issue by bcmpinc** [CyclopsMC/CommonCapabilitiesAPI#6]
When `org.cyclops.commoncapabilities.api.capability.itemhandler.ItemMatch.areItemStackTagsEqual`is passed arguments such that `a.getTagCompound() != null && b.getTagCompound() == null` this results in `NBT_COMPARATOR.compare` being called with a `null` argument, which it does not support and leads to a null pointer exception followed by a crash.

**Comment by rubensworks** [comment]
Huh, that looks wrong indeed.
