### ISSUE TITLE
Freshly built Energy Batteries aren't handled very well

### ISSUE THREAD

**Issue by TomyLobo** [CyclopsMC/CommonCapabilitiesAPI#8]
1. Sometimes the Storage Terminal doesn't show them
2. If it does show them, it doesn't allow extracting them
3. When creating a recipe for them using the JEI recipe transfer feature (the little "+" button), that recipe cannot be crafted:
![image](https://user-images.githubusercontent.com/963797/69722489-93370d00-1117-11ea-9937-71268a45b02e.png)
4. When crafting a manually created recipe, the system doesn't recognize the result
5. Crafting chains involving those batteries are nearly impossible to make due to this

I did some analysis with CraftTweaker's "/ct nbt" command and the difference between the recipes created manually and using JEI recipe transfer is this:
JEI recipe transfer:
```json
{
    _type: "valuetype",
     typeName: "valuetype.valuetypes.integrateddynamics.recipe.name",
     _id: 256,
     value: "{output:{\"minecraft:itemstack\":[{id:\"integrateddynamics:energy_battery\",Count:1b,Damage:0s}]},input:{\"minecraft:itemstack\":[{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"minecraft:redstone_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b}]}}"
}
```
manually created:
```json
{
    _type: "valuetype",
     typeName: "valuetype.valuetypes.integrateddynamics.recipe.name",
     _id: 759,
     value: "{output:{\"minecraft:itemstack\":[{id:\"integrateddynamics:energy_battery\",Count:1b,tag:{},Damage:0s}]},input:{\"minecraft:itemstack\":[{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"minecraft:redstone_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_block\",Count:1b,Damage:0s}}],type:0b},{val:[{condition:3,prototype:{id:\"integrateddynamics:crystalized_menril_chunk\",Count:1b,Damage:0s}}],type:0b}]}}"
}
```
The only difference between them is the `tag:{},` in the output.

I think JEI just enters what it sees in the actual recipe definition as the output, whereas any actually existing battery would already have the empty tag in place.

Proposed solution:
1. Make the recipe create a battery with the "energy" tag already initialized to 0, thus avoiding confusing between having an empty tag container and no tag container
2. For good measure, ensure that JEI-cheated items also contain that tag

**Comment by TomyLobo** [comment]
My workaround:
1. Craft the battery using some external autocrafter (in my case autoverse's)
2. Discharge the battery (in my case using the Actually Additions Enervator)
3. Return it to the system

This needs a modified recipe, for the battery and everything that needs a battery as part of its ingredients.
Here's my setup:
![image](https://user-images.githubusercontent.com/963797/69723349-9df2a180-1119-11ea-824b-d7cbc22c5884.png)

**Comment by rubensworks** [comment]
Nice find!

**Comment by TomyLobo** [comment]
I just hope I didn't spam #⌨-development  too much :D
